framework:
  session:
    cookie_lifetime: null
    cookie_secure: auto
    cookie_samesite: lax
    gc_probability : 1
    gc_divisor : 100
    handler_id: session.handler.native_file
    save_path: '/opt/bitnami/php/var/run/session'
